# Generated by Django 2.2.5 on 2019-09-19 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_admin', models.TextField(max_length=200)),
                ('contrasena', models.TextField(max_length=200)),
                ('correo', models.EmailField(max_length=200)),
                ('telefono', models.TextField(max_length=200)),
                ('municipio', models.TextField(max_length=200)),
                ('descripcion', models.TextField(max_length=600)),
                ('imagen', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='contactenos',
            fields=[
                ('id_contactenos', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=200)),
                ('sugerencia', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.TextField(max_length=200)),
                ('razon_social', models.TextField(max_length=100)),
                ('municipio', models.TextField(max_length=60)),
                ('tipo_servicio', models.TextField(max_length=190)),
                ('direccion', models.TextField(max_length=90)),
                ('telefono', models.TextField(max_length=50)),
                ('correo', models.EmailField(max_length=250)),
                ('contrasena', models.TextField(max_length=70)),
                ('imagen', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='turista',
            fields=[
                ('id_turista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=200)),
                ('apellido', models.TextField(max_length=200)),
                ('correo', models.EmailField(max_length=250)),
                ('telefono', models.TextField(max_length=50)),
                ('edad', models.IntegerField(null=True)),
                ('estado_Civil', models.TextField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Union libre', 'UnionLibre')], default='Soltero')),
                ('gustos', models.TextField(max_length=200)),
                ('limitaciones', models.TextField(max_length=200)),
                ('ocupacion', models.TextField(max_length=200)),
                ('contrasena', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=200)),
                ('tipo_servicio', models.TextField(max_length=200)),
                ('cantidad_personas', models.IntegerField(null=True)),
                ('precio_persona', models.FloatField(null=True)),
                ('descripcion', models.TextField(max_length=200)),
                ('imagen', models.TextField(max_length=200)),
                ('puntiacion', models.IntegerField(null=True)),
                ('proveedor_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villeta.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('valor', models.FloatField(null=True)),
                ('cantidad_personas', models.IntegerField(null=True)),
                ('pago', models.TextField(max_length=200)),
                ('razon_social', models.TextField(max_length=200)),
                ('id_servicio', models.IntegerField(null=True)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villeta.proveedor')),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villeta.turista')),
            ],
        ),
        migrations.CreateModel(
            name='comentario_Servicio',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Usuario', models.TextField(max_length=200)),
                ('comentario', models.TextField(max_length=700)),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villeta.servicio')),
            ],
        ),
    ]
